version: '3.9'
services:
  redis:
    image: redis
    volumes:
        - data:/data
  web:
    image: marlont876/userapidocker-mt
#    image: useratest-mt
    # COMPLETE HERE
    build: .
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
        - redis
volumes:
   data: