FROM keymetrics/pm2:latest-alpine
WORKDIR /usr/src/app
# Bundle APP files
COPY ./userapi/ .
COPY ./userapi/package*.json ./
COPY ./userapi/ecosystem.config.js ./

# Install app dependencies
ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install 

# Expose the listening port of your app
EXPOSE 3000

# Show current folder structure in logs
RUN ls -al -R

CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]