apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi-deployment
  labels:
    app: userapi
spec:
  replicas: 2
  # TO COMPLETE #2
  selector:
   matchLabels:
    pp: userapi
  template:
   metadata:
    labels:
    app: userapi
    spec:
    containers:
    - name: userapi
    image: userapidocker-mt
    ports:
    - containerPort: 3000
    - env:
    - name: REDIS_HOST
    value: redis
    - name: REDIS_PORT
    value: "6379"
    resources: {}
    restartPolicy: Always
status: {}