apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 3000
  selector:
    app: web
# status:
  # loadBalancer: {}
