---
- 
 hosts: localhost
  become: yes
  gather_facts: no
  vars:
      repo_url: https://github.com/marlonvets/DSTI_DevopsProject.git
      repo_path: /srv/userapi
      repo_branch: main
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
   update_cache: yes
- name: Ansible shell module multiple commands
    shell: 'curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -'
- name: Install reqired packages
    apt: name={{ item }} state=present
    with_items:
      - git
      - wget
      - nodejs
- name: Clone a private repository
    git:
         repo: "{{ git_repo_url }}"
         dest: "{{ repo_path }}"
         version: "{{ repo_branch }}"
         accept_hostkey: yes

- name: Install packages based on package.json using the npm
    npm:
      path: "{{ repo_path }}"
      state: present
  - name: Build app
    command: npm run build
    args:
      chdir: "{{ repo_path }}"


- name: Install userapi

  environment:
    EXTERNAL_URL: http://userapi.local
