- name: Install required packages
  yum:
    name:
      - curl
      - policycoreutils-python
      - openssh-server
      - git
      - wget
      - nodejs
      - npm
      - redis
    state: latest

- name: Enable and start sshd
  service:
    name: sshd
    state: started
    enabled: yes
    
- name: Start Redis
  service:
    name: redis
    state: started
    enabled: yes
    
- name: Install packages based on package.json.
  npm:
    path: /tmp/app

- name: Run test for app
  ansible.builtin.shell:
    cmd: npm test
    chdir: /tmp/app/

# - name: Run test for packages
  # ansible.builtin.shell:
    # cmd: vagrant rsync-auto
    
- name: This command will start the application
  ansible.builtin.shell:
    cmd: npm start
    chdir: /tmp/app/